Repository williamphelps13/rancid-tomatillos, pull requests merged in 2021-09, with the labels that each got.

#29 Feature/router
  package-lock.json
  package.json
  src/App.js
  src/Movie.js
  src/Posters.js
  src/index.js
Labels: enhancement

#30 Refactor/router match
  src/App.js
  src/Movie.js
  src/Posters.js
Labels: enhancement, api

#31 Feature/loader
  src/App.js
  src/Error.css
  src/Error.js
  src/Loader.css
  src/Loader.js
  src/Movie.js
  src/error.png
  src/loader.jpg
Labels: enhancement

#32 Feature/css
  src/App.css
  src/Movie.css
  src/Movie.js
  src/Posters.css
Labels: enhancement

#33 Refactor/testing
  cypress/fixtures/example.json
  cypress/fixtures/movie_test_data.json
  cypress/fixtures/posters_test_data.json
  cypress/integration/movie_spec.js
  cypress/integration/posters_spec.js
  cypress/support/commands.js
  src/Movie.js
Labels: testing

#34 Feature/movie
  src/App.css
  src/Movie.css
  src/Movie.js
  src/Posters.css
Labels: enhancement

#35 Refactor/api
  src/App.js
  src/Error.js
  src/Movie.js
  src/apiCalls.js
  src/data-cleaning.js
Labels: enhancement, api

#37 Feature/movie
  src/Loader.css
  src/Loader.js
  src/Movie.css
  src/Movie.js
  src/data-cleaning.js
Labels: enhancement

#36 Add favicon
  public/favicon.ico
Labels: enhancement

#38 Feature/readme
  README.md
Labels: documentation

#41 Refactor/overview
  cypress/integration/api_calls_spec.js
  cypress/integration/movie_spec.js
  cypress/integration/posters_spec.js
  cypress/support/commands.js
  src/App.js
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/Error/Error.css
  src/Components/Error/Error.js
  src/Components/Error/error.png
  src/Components/Loader/Loader.css
  src/Components/Loader/Loader.js
  src/Components/Loader/loader.jpg
  src/Components/Movie/Movie.css
  src/Components/Movie/Movie.js
  src/Components/Posters/Posters.css
  src/Components/Posters/Posters.js
  src/Movie/Movie.js
  src/child-components/Movie/Movie.js
  src/index.js
  src/utilities/apiCalls.js
  src/utilities/dataCleaning.js
Labels: enhancement, api, testing

#44 Fix scrolling bug
  src/Components/Movie/Movie.css
Labels: bug

#43 Feature/readme
  README.md
Labels: documentation
