Repository williamphelps13/rancid-tomatillos, pull requests merged in 2021-08, with the labels that each got.

#21 Feature/movie fetch
  src/App.css
  src/App.js
  src/Movie.css
  src/Posters.js
Labels: enhancement, api

#22 Feature/error handling
  package-lock.json
  package.json
  src/App.js
  src/apiCalls.js
Labels: enhancement, api

#23 Refactor/destructure
  src/Movie.css
  src/Movie.js
  src/Posters.js
Labels: enhancement

#24 Test/posters
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/posters_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
Labels: testing

#28 Test/movie
  cypress/integration/movie_spec.js
  cypress/integration/posters_spec.js
Labels: testing
